package pw.binom

object Versions {
    val HTTP_VERSION = BuildConfig.HTTP_CLIENT_VERSION
    val KOTLIN_VERSION = BuildConfig.KOTLIN_VERSION
    val KOTLINX_SERIALIZATION_VERSION = BuildConfig.KOTLINX_SERIALIZATION_VERSION
    val KOTLINX_COROUTINES_VERSION = BuildConfig.KOTLINX_COROUTINES_VERSION
}
